Repository vercel/ai, pull requests merged in 2025-10, with the labels that each got.

#9040 refactor(deepinfra): sort model IDs
  packages/deepinfra/src/deepinfra-chat-options.ts
Labels: feature request, provider/other, backport

#9099 fix: update migration guide for strict mode and structured output changes
  content/docs/08-migration-guides/26-migration-guide-5-0.mdx
Labels: backport

#9125 Backport: chore(ai): update README to use npm install#9105
  packages/ai/README.md
Labels: documentation

#9080 docs(observability): add Sentry
  content/providers/05-observability/index.mdx
Labels: backport

#9176 feat(provider/azure): default api-version has changed from preview to v1
  .changeset/rich-boats-yawn.md
  content/providers/01-ai-sdk-providers/04-azure.mdx
  examples/ai-core/src/embed-many/azure.ts
  examples/ai-core/src/embed/azure.ts
  examples/ai-core/src/generate-image/azure.ts
  examples/ai-core/src/generate-object/azure.ts
  examples/ai-core/src/generate-speech/azure.ts
  examples/ai-core/src/generate-text/azure-custom-fetch.ts
  examples/ai-core/src/generate-text/azure-image.ts
  examples/ai-core/src/generate-text/azure-responses-code-interpreter.ts
  examples/ai-core/src/generate-text/azure-responses-file-id.ts
  examples/ai-core/src/generate-text/azure-responses-file-search.ts
  examples/ai-core/src/generate-text/azure-responses-pdf.ts
  examples/ai-core/src/generate-text/azure-responses-reasoning-summary.ts
  examples/ai-core/src/generate-text/azure-responses.ts
  examples/ai-core/src/generate-text/azure.ts
  examples/ai-core/src/stream-object/azure.ts
  examples/ai-core/src/stream-text/azure-completion.ts
  examples/ai-core/src/stream-text/azure-fullstream-logprobs.ts
  examples/ai-core/src/stream-text/azure-fullstream.ts
  examples/ai-core/src/stream-text/azure-responses-code-interpreter.ts
  examples/ai-core/src/stream-text/azure-responses-file-id.ts
  examples/ai-core/src/stream-text/azure-responses-file-search.ts
  examples/ai-core/src/stream-text/azure-responses-pdf.ts
  examples/ai-core/src/stream-text/azure-responses-reasoning-summary.ts
  examples/ai-core/src/stream-text/azure-smooth-line.ts
  examples/ai-core/src/stream-text/azure-smooth.ts
  examples/ai-core/src/stream-text/azure.ts
  examples/ai-core/src/transcribe/azure-deployment-based.ts
  examples/ai-core/src/transcribe/azure-string.ts
  examples/ai-core/src/transcribe/azure-url.ts
  examples/ai-core/src/transcribe/azure.ts
  packages/azure/src/azure-openai-provider.test.ts
  packages/azure/src/azure-openai-provider.ts
Labels: backport

#9215 feat(provider/openai): add new model IDs `gpt-image-1-mini`, `gpt-5-pro`, `gpt-5-pro-2025-10-06`
  .changeset/real-coats-kick.md
  content/providers/01-ai-sdk-providers/03-openai.mdx
  examples/ai-core/src/generate-image/openai.ts
  examples/ai-core/src/generate-text/openai.ts
  packages/openai/src/image/openai-image-options.ts
  packages/openai/src/responses/openai-responses-settings.ts
Labels: feature request, provider/openai, backport

#9223 ci(auto-merge-release-prs): use PAT to approve "version packages" prs
  .github/workflows/auto-merge-release-prs.yml
Labels: backport

#9181 fix(provider/openai): add providerExecuted flag to tool start chunks
  .changeset/odd-donkeys-kick.md
  packages/openai/src/responses/__snapshots__/openai-responses-language-model.test.ts.snap
  packages/openai/src/responses/openai-responses-language-model.test.ts
  packages/openai/src/responses/openai-responses-language-model.ts
Labels: backport

#9199 docs: use `inputSchema` instead of `parameters` for tools
  content/docs/03-agents/01-overview.mdx
Labels: backport

#9245 docs: refactor agents section around stabilised agent class
  content/docs/03-agents/01-overview.mdx
  content/docs/03-agents/02-building-agents.mdx
  content/docs/03-agents/03-workflows.mdx
  content/docs/03-agents/04-loop-control.mdx
  content/docs/03-agents/index.mdx
Labels: backport

#9251 Prepare ai SDK v6 (beta) release
  .changeset/clean-elephants-tickle.md
Labels: major

#9258 Update Cerebras Models
  .changeset/few-bottles-allow.md
  packages/cerebras/CHANGELOG.md
  packages/cerebras/README.md
  packages/cerebras/package.json
  packages/cerebras/src/cerebras-chat-options.ts
  packages/cerebras/tsconfig.json
  packages/cerebras/turbo.json
Labels: backport
