Repository vercel/ai, pull requests merged in 2025-07, with the labels that each got.

#7181 docs: add jigsawstack as tools
  content/docs/02-foundations/04-tools.mdx
Labels: docs

#7211 feat (angular): Add Angular support and example
  .changeset/nasty-avocados-sort.md
  examples/angular/.gitignore
  examples/angular/README.md
  examples/angular/angular.json
  examples/angular/package.json
  examples/angular/proxy.conf.json
  examples/angular/public/favicon.ico
  examples/angular/src/app/app.component.ts
  examples/angular/src/app/app.config.ts
  examples/angular/src/app/app.routes.ts
  examples/angular/src/app/chat/chat.component.css
  examples/angular/src/app/chat/chat.component.html
  examples/angular/src/app/chat/chat.component.ts
  examples/angular/src/app/completion/completion.component.css
  examples/angular/src/app/completion/completion.component.ts
  examples/angular/src/app/structured-object/structured-object.component.css
  examples/angular/src/app/structured-object/structured-object.component.ts
  examples/angular/src/index.html
  examples/angular/src/main.ts
  examples/angular/src/server.ts
  examples/angular/src/styles.css
  examples/angular/tsconfig.app.json
  examples/angular/tsconfig.json
  examples/angular/tsconfig.server.json
  packages/angular/README.md
  packages/angular/package.json
  packages/angular/src/index.ts
  packages/angular/src/lib/chat.ng.test.ts
  packages/angular/src/lib/chat.ng.ts
  packages/angular/src/lib/completion.ng.test.ts
  packages/angular/src/lib/completion.ng.ts
  packages/angular/src/lib/structured-object.ng.test.ts
  packages/angular/src/lib/structured-object.ng.ts
  packages/angular/tsconfig.build.json
  packages/angular/tsconfig.json
  packages/angular/tsup.config.ts
  packages/angular/vitest.config.ts
  pnpm-lock.yaml
  tsconfig.json
  tsconfig.with-examples.json
Labels: major

#7282 fix (ai): throw error for v2 models or string model ids
  .changeset/afraid-readers-bow.md
  packages/ai/core/embed/embed-many.ts
  packages/ai/core/embed/embed.ts
  packages/ai/core/generate-image/generate-image.ts
  packages/ai/core/generate-object/generate-object.ts
  packages/ai/core/generate-object/stream-object.ts
  packages/ai/core/generate-speech/generate-speech.ts
  packages/ai/core/generate-text/generate-text.ts
  packages/ai/core/generate-text/stream-text.ts
  packages/ai/core/transcribe/transcribe.ts
  packages/ai/errors/index.ts
  packages/ai/errors/unsupported-model-version-error.ts
Labels: v4

#7356 [docs] Fix transport: key
  content/cookbook/01-next/73-mcp-tools.mdx
  content/cookbook/05-node/54-mcp-tools.mdx
Labels: docs

#7462 feat (docs): add signoz observability as a provider
  content/providers/05-observability/index.mdx
  content/providers/05-observability/signoz.mdx
Labels: docs
