Repository vercel/ai, pull requests merged in 2025-09, with the labels that each got.

#8383 docs: document prompt array messages
  content/docs/07-reference/01-ai-sdk-core/01-generate-text.mdx
  content/docs/07-reference/01-ai-sdk-core/02-stream-text.mdx
  content/docs/07-reference/01-ai-sdk-core/03-generate-object.mdx
  content/docs/07-reference/01-ai-sdk-core/04-stream-object.mdx
Labels: codex

#8299 test: auto update fixture output
  packages/codemod/package.json
  packages/codemod/src/test/rename-message-to-ui-message.test.ts
  packages/codemod/src/test/replace-generatetext-text-property.test.ts
  packages/codemod/src/test/test-utils.test.ts
  packages/codemod/src/test/test-utils.ts
  packages/codemod/turbo.json
Labels: ai/codemod

#8352 docs: add on-device apple provider
  content/providers/03-community-providers/90-react-native-apple.mdx
Labels: provider/community

#8446 feat(provider/gateway): Add Voyage embedding models
  .changeset/unlucky-squids-carry.md
  packages/gateway/src/gateway-embedding-model-settings.ts
Labels: ai/gateway

#8463 fix(openai): update timestamp_granularities to array format
  .changeset/light-dogs-lie.md
  packages/openai/src/transcription/openai-transcription-model.test.ts
  packages/openai/src/transcription/openai-transcription-model.ts
Labels: bug, provider/openai

#8640 ci(publis): do not run in forks
  .github/workflows/release.yml
Labels: maintenance

#8680 feat(ai): add safeValidateUIMessages
  .changeset/red-roses-glow.md
  content/docs/07-reference/01-ai-sdk-core/33-safe-validate-ui-messages.mdx
  packages/ai/src/ui/index.ts
  packages/ai/src/ui/validate-ui-messages.test.ts
  packages/ai/src/ui/validate-ui-messages.ts
Labels: feature request, ai/core, backport

#8737 added baseten to website docs
  content/cookbook/00-guides/21-llama-3_1.mdx
  content/docs/02-foundations/02-providers-and-models.mdx
  content/providers/01-ai-sdk-providers/170-baseten.mdx
  content/providers/01-ai-sdk-providers/index.mdx
  content/providers/02-openai-compatible-providers/40-baseten.mdx
  content/providers/02-openai-compatible-providers/index.mdx
Labels: documentation, backport

#8785 feat (provider/cerebras): enable structured outputs
  .changeset/grumpy-actors-sleep.md
  examples/ai-core/src/generate-object/cerebras.ts
  examples/ai-core/src/stream-object/cerebras.ts
  packages/cerebras/src/cerebras-provider.ts
Labels: backport

#8801 feat(xai): add grok-4-fast model ids
  .changeset/two-birds-agree.md
  content/providers/01-ai-sdk-providers/01-xai.mdx
  packages/xai/src/xai-chat-options.ts
Labels: backport

#8212 feat(provider/openai): `OpenAILanguageModelOptions` type
  .changeset/cyan-mirrors-clap.md
  content/providers/01-ai-sdk-providers/03-openai.mdx
  examples/ai-core/src/generate-text/openai-provider-options.ts
  packages/openai/src/chat/openai-chat-language-model.ts
  packages/openai/src/chat/openai-chat-options.ts
  packages/openai/src/index.ts
Labels: backport

#8560 feat(ai): extend addToolResult to support error results
  .changeset/long-dodos-lay.md
  content/docs/04-ai-sdk-ui/03-chatbot-tool-usage.mdx
  content/docs/07-reference/02-ai-sdk-ui/01-use-chat.mdx
  content/docs/09-troubleshooting/05-tool-invocation-missing-result.mdx
  packages/ai/src/ui/chat.test.ts
  packages/ai/src/ui/chat.ts
  packages/ai/src/ui/last-assistant-message-is-complete-with-tool-calls.test.ts
  packages/ai/src/ui/last-assistant-message-is-complete-with-tool-calls.ts
Labels: backport

#8918 fix(ai): minor type fix
  packages/ai/src/ui/chat.ts
Labels: ai/core, ai/codemod, backport

#8920 fix: update zod peer dependency version range
  .changeset/six-needles-suffer.md
  packages/ai/package.json
  packages/amazon-bedrock/package.json
  packages/angular/package.json
  packages/anthropic/package.json
  packages/assemblyai/package.json
  packages/azure/package.json
  packages/baseten/package.json
  packages/cerebras/package.json
  packages/cohere/package.json
  packages/deepgram/package.json
  packages/deepinfra/package.json
  packages/deepseek/package.json
  packages/elevenlabs/package.json
  packages/fal/package.json
  packages/fireworks/package.json
  packages/gateway/package.json
  packages/gladia/package.json
  packages/google-vertex/package.json
  packages/google/package.json
  packages/groq/package.json
  packages/hume/package.json
  packages/lmnt/package.json
  packages/luma/package.json
  packages/mistral/package.json
  packages/openai-compatible/package.json
  packages/openai/package.json
  packages/perplexity/package.json
  packages/provider-utils/package.json
  packages/react/package.json
  packages/replicate/package.json
  packages/revai/package.json
  packages/rsc/package.json
  packages/svelte/package.json
  packages/togetherai/package.json
  packages/vercel/package.json
  packages/vue/package.json
  packages/xai/package.json
  pnpm-lock.yaml
Labels: backport

#8926 chore (provider/google): Add preview modelIds for gemini 2.5 flash and lite
  .changeset/witty-items-rest.md
  packages/google-vertex/src/google-vertex-options.ts
  packages/google/src/google-generative-ai-options.ts
Labels: feature request, provider/google, backport

#8936 feat(provider/openai): only send item references for reasoning when store: true
  .changeset/pretty-spies-cheer.md
  examples/next-openai/app/api/use-chat-reasoning/route.ts
  packages/openai/src/responses/convert-to-openai-responses-input.test.ts
  packages/openai/src/responses/convert-to-openai-responses-input.ts
Labels: backport

#8942 feat(provider/anthropic): web search tool updates
  .changeset/dull-ladybugs-clap.md
  content/providers/01-ai-sdk-providers/05-anthropic.mdx
  examples/ai-core/src/generate-text/anthropic-web-search-tool.ts
  examples/ai-core/src/generate-text/anthropic-web-search.ts
  examples/ai-core/src/stream-text/anthropic-web-search-tool.ts
  examples/ai-core/src/stream-text/anthropic-web-search.ts
  examples/next-openai/app/anthropic-web-search/page.tsx
  examples/next-openai/app/api/anthropic-web-search/route.ts
  examples/next-openai/app/test-openai-web-search/page.tsx
  examples/next-openai/component/anthropic-web-search-view.tsx
  packages/anthropic/src/__fixtures__/anthropic-web-search-tool.1.chunks.txt
  packages/anthropic/src/__fixtures__/anthropic-web-search-tool.1.json
  packages/anthropic/src/__snapshots__/anthropic-messages-language-model.test.ts.snap
  packages/anthropic/src/anthropic-messages-language-model.test.ts
  packages/anthropic/src/convert-to-anthropic-messages-prompt.test.ts
  packages/anthropic/src/tool/web-search_20250305.ts
Labels: backport

#8946 feat(provider/anthropic): add web fetch tool
  .changeset/pretty-boats-care.md
  content/providers/01-ai-sdk-providers/05-anthropic.mdx
  examples/ai-core/src/generate-text/anthropic-web-fetch-tool-pdf.ts
  examples/ai-core/src/generate-text/anthropic-web-fetch-tool-wikipedia.ts
  examples/ai-core/src/generate-text/anthropic-web-search-tool.ts
  examples/ai-core/src/stream-text/anthropic-web-fetch-tool-pdf.ts
  examples/ai-core/src/stream-text/anthropic-web-fetch-tool-wikipedia.ts
  examples/next-openai/app/anthropic-web-fetch/page.tsx
  examples/next-openai/app/api/anthropic-web-fetch/route.ts
  examples/next-openai/component/anthropic-web-fetch-view.tsx
  packages/anthropic/src/__fixtures__/anthropic-web-fetch-tool.1.chunks.txt
  packages/anthropic/src/__fixtures__/anthropic-web-fetch-tool.1.json
  packages/anthropic/src/__fixtures__/anthropic-web-fetch-tool.error.json
  packages/anthropic/src/__snapshots__/anthropic-messages-language-model.test.ts.snap
  packages/anthropic/src/anthropic-api-types.ts
  packages/anthropic/src/anthropic-messages-language-model.test.ts
  packages/anthropic/src/anthropic-messages-language-model.ts
  packages/anthropic/src/anthropic-prepare-tools.test.ts
  packages/anthropic/src/anthropic-prepare-tools.ts
  packages/anthropic/src/anthropic-tools.ts
  packages/anthropic/src/convert-to-anthropic-messages-prompt.test.ts
  packages/anthropic/src/convert-to-anthropic-messages-prompt.ts
  packages/anthropic/src/tool/web-fetch-20250910.ts
Labels: backport

#7788 feat(huggingface): add responses api support
  .changeset/curly-planes-film.md
  content/providers/01-ai-sdk-providers/170-huggingface.mdx
  content/providers/01-ai-sdk-providers/index.mdx
  examples/ai-core/package.json
  examples/ai-core/src/e2e/huggingface.test.ts
  examples/ai-core/src/generate-object/huggingface.ts
  examples/ai-core/src/generate-text/huggingface-multi-message.ts
  examples/ai-core/src/generate-text/huggingface-multi-step.ts
  examples/ai-core/src/generate-text/huggingface-multimodal.ts
  examples/ai-core/src/generate-text/huggingface-reasoning-input.ts
  examples/ai-core/src/generate-text/huggingface-reasoning.ts
  examples/ai-core/src/generate-text/huggingface-responses-annotations.ts
  examples/ai-core/src/generate-text/huggingface-responses.ts
  examples/ai-core/src/generate-text/huggingface-system-message.ts
  examples/ai-core/src/generate-text/huggingface-temperature.ts
  examples/ai-core/src/generate-text/huggingface-tools.ts
  examples/ai-core/src/stream-object/huggingface.ts
  examples/ai-core/src/stream-text/huggingface-multi-message.ts
  examples/ai-core/src/stream-text/huggingface-multimodal.ts
  examples/ai-core/src/stream-text/huggingface-reasoning-input.ts
  examples/ai-core/src/stream-text/huggingface-reasoning.ts
  examples/ai-core/src/stream-text/huggingface-responses.ts
  examples/ai-core/src/stream-text/huggingface-system-message.ts
  examples/ai-core/src/stream-text/huggingface-temperature.ts
  examples/ai-core/src/stream-text/huggingface-tools.ts
  packages/huggingface/README.md
  packages/huggingface/package.json
  packages/huggingface/src/huggingface-config.ts
  packages/huggingface/src/huggingface-error.ts
  packages/huggingface/src/huggingface-provider.test.ts
  packages/huggingface/src/huggingface-provider.ts
  packages/huggingface/src/index.ts
  packages/huggingface/src/responses/convert-to-huggingface-responses-messages.ts
  packages/huggingface/src/responses/huggingface-responses-language-model.test.ts
  packages/huggingface/src/responses/huggingface-responses-language-model.ts
  packages/huggingface/src/responses/huggingface-responses-prepare-tools.ts
  packages/huggingface/src/responses/huggingface-responses-settings.ts
  packages/huggingface/src/responses/map-huggingface-responses-finish-reason.ts
  packages/huggingface/tsconfig.build.json
  packages/huggingface/tsconfig.json
  packages/huggingface/tsup.config.ts
  packages/huggingface/turbo.json
  packages/huggingface/vitest.edge.config.js
  packages/huggingface/vitest.node.config.js
  pnpm-lock.yaml
  tsconfig.json
Labels: major

#8586 feat(codemod): add tool invocations migration to v5 codemods
  .changeset/stale-keys-laugh.md
  packages/codemod/src/codemods/v5/not-implemented/move-tool-invocations-to-parts.ts
  packages/codemod/src/lib/upgrade.ts
  packages/codemod/src/test/__testfixtures__/move-tool-invocations-to-parts.input.ts
  packages/codemod/src/test/__testfixtures__/move-tool-invocations-to-parts.output.ts
  packages/codemod/src/test/move-tool-invocations-to-parts.test.ts
Labels: backport

#8512 fix(ai): update docs for NoSpeechGeneratedError and export it
  .changeset/late-emus-explode.md
  content/docs/03-ai-sdk-core/37-speech.mdx
  content/docs/07-reference/05-ai-sdk-errors/ai-no-audio-generated-error.mdx
  content/docs/07-reference/05-ai-sdk-errors/ai-no-speech-generated-error.mdx
  content/docs/07-reference/05-ai-sdk-errors/index.mdx
  packages/ai/src/error/index.ts
Labels: backport

#8725 feat(codemod): add usechat input state transformation for v5
  .changeset/silent-queens-count.md
  packages/codemod/README.md
  packages/codemod/src/codemods/v5/replace-usechat-input-with-state.ts
  packages/codemod/src/lib/upgrade.ts
  packages/codemod/src/test/__testfixtures__/replace-usechat-input-with-state.input.ts
  packages/codemod/src/test/__testfixtures__/replace-usechat-input-with-state.output.ts
  packages/codemod/src/test/replace-usechat-input-with-state.test.ts
Labels: backport

#8732 feat(codemod): add usechat api to transport transformation
  .changeset/slow-houses-fail.md
  packages/codemod/README.md
  packages/codemod/src/codemods/v5/replace-usechat-api-with-transport.ts
  packages/codemod/src/lib/upgrade.ts
  packages/codemod/src/test/__testfixtures__/replace-usechat-api-with-transport.input.ts
  packages/codemod/src/test/__testfixtures__/replace-usechat-api-with-transport.output.ts
  packages/codemod/src/test/replace-usechat-api-with-transport.test.ts
Labels: backport

#8979 docs(examples/angular): bump angular dependencies to latest
  examples/angular/package.json
  pnpm-lock.yaml
Labels: backport

#8998 fix(provider/anthropic): support null title in web fetch tool
  .changeset/unlucky-pots-sniff.md
  examples/ai-core/src/generate-text/anthropic-web-fetch-tool-pdf.ts
  examples/ai-core/src/stream-text/anthropic-web-fetch-tool-pdf.ts
  packages/anthropic/src/__fixtures__/anthropic-web-fetch-tool.2.json
  packages/anthropic/src/__snapshots__/anthropic-messages-language-model.test.ts.snap
  packages/anthropic/src/anthropic-messages-language-model.test.ts
  packages/anthropic/src/anthropic-messages-language-model.ts
Labels: backport

#9006 feat(provider/openai): add gpt-5-codex model id
  .changeset/little-penguins-smell.md
  content/docs/02-foundations/02-providers-and-models.mdx
  content/providers/01-ai-sdk-providers/03-openai.mdx
  content/providers/01-ai-sdk-providers/index.mdx
  examples/ai-core/src/stream-text/openai-codex.ts
  packages/openai/src/responses/openai-responses-settings.ts
Labels: backport

#9009 feat(provider/openai): local shell tool
  .changeset/poor-ligers-own.md
  content/providers/01-ai-sdk-providers/03-openai.mdx
  examples/ai-core/src/generate-text/openai-local-shell-tool.ts
  examples/ai-core/src/lib/run.ts
  examples/ai-core/src/stream-text/openai-local-shell-tool.ts
  examples/next-openai/app/api/chat-openai-local-shell/route.ts
  examples/next-openai/app/test-openai-local-shell/page.tsx
  examples/next-openai/component/openai-local-shell-view.tsx
  examples/next-openai/package.json
  packages/openai/src/openai-tools.ts
  packages/openai/src/responses/__fixtures__/openai-local-shell-tool.1.chunks.txt
  packages/openai/src/responses/__fixtures__/openai-local-shell-tool.1.json
  packages/openai/src/responses/__snapshots__/openai-responses-language-model.test.ts.snap
  packages/openai/src/responses/convert-to-openai-responses-input.test.ts
  packages/openai/src/responses/convert-to-openai-responses-input.ts
  packages/openai/src/responses/openai-responses-api-types.ts
  packages/openai/src/responses/openai-responses-language-model.test.ts
  packages/openai/src/responses/openai-responses-language-model.ts
  packages/openai/src/responses/openai-responses-prepare-tools.test.ts
  packages/openai/src/responses/openai-responses-prepare-tools.ts
  packages/openai/src/tool/local-shell.ts
  pnpm-lock.yaml
Labels: backport

#8813 docs: update createUIMessageStream example to use v5 API format
  content/docs/07-reference/02-ai-sdk-ui/40-create-ui-message-stream.mdx
Labels: documentation

#8894 feat (docs): Add supermemory community provider
  content/docs/02-foundations/02-providers-and-models.mdx
  content/providers/03-community-providers/72-supermemory.mdx
Labels: documentation, backport

#9038 feat(provider/gateway): Add DeepSeek V3.2 Exp to Gateway language model settings
  .changeset/itchy-boxes-hang.md
  packages/gateway/src/gateway-language-model-settings.ts
Labels: backport

#8990 feat(provider/openai): allow configuring base URL via OPENAI_BASE_URL
  .changeset/curvy-foxes-sniff.md
  packages/openai/src/openai-provider.test.ts
  packages/openai/src/openai-provider.ts
  turbo.json
Labels: feature request, provider/openai, backport

#9066 feat(amazon-bedrock): add Claude Sonnet 4.5 model support
  .changeset/strong-seas-rush.md
  content/providers/01-ai-sdk-providers/08-amazon-bedrock.mdx
  packages/amazon-bedrock/src/bedrock-chat-options.ts
Labels: backport

#9095 Baseten docs update
  content/providers/01-ai-sdk-providers/170-baseten.mdx
  content/providers/01-ai-sdk-providers/index.mdx
Labels: documentation, provider/other, backport
